### ISSUE TITLE
Agregar permisos a "Encargado" para el endpoint de reservations/reasons

### ISSUE THREAD

**Issue by Sega1A** [BruteForceSolutionsSRL/reservation-system-back#62]
Para una reserva especial, es necesario que el encargado tenga permisos al endpoint.

![image](https://github.com/BruteForceSolutionsSRL/reservation-system-back/assets/67697132/f0e0fe20-9a04-47e1-85ec-b77c17e3f7d2)

**Comment by Emerson-DVV** [comment]
![image](https://github.com/BruteForceSolutionsSRL/reservation-system-back/assets/67840383/28eed12b-145f-4d94-9868-4866534e61f6)
![image](https://github.com/BruteForceSolutionsSRL/reservation-system-back/assets/67840383/1731ddb5-c603-4079-86d4-8054b59ea862)
